# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relicta < Formula
  desc "AI-powered release governance for modern software teams"
  homepage "https://github.com/relicta-tech/relicta"
  version "4.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
       url "https://github.com/relicta-tech/relicta/releases/download/v4.0.3/relicta_darwin_amd64.tar.gz"
       sha256 "39d01b3a078885242dc081c4812265d21f1f747cfd4a0208b054d7c545487a51"

      def install
        bin.install "relicta"
      end
    end
    if Hardware::CPU.arm?
       url "https://github.com/relicta-tech/relicta/releases/download/v4.0.3/relicta_darwin_arm64.tar.gz"
       sha256 "5c2183b27ef1b2316a9631c0e5d7ca6693221f3a6c2e6482a063c75d5b0685f3"

      def install
        bin.install "relicta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
       url "https://github.com/relicta-tech/relicta/releases/download/v4.0.3/relicta_linux_amd64.tar.gz"
       sha256 "db299a9d01dbd21cdec4bc88f2fe5a7f946949566d9e26f18789a28437207854"

      def install
        bin.install "relicta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
       url "https://github.com/relicta-tech/relicta/releases/download/v4.0.3/relicta_linux_arm64.tar.gz"
       sha256 "7dd2df609c2fa5c45b64d67d2f915093bb1b7494b451baa2945c8bed093f2a04"

      def install
        bin.install "relicta"
      end
    end
  end

  test do
    system "#{bin}/relicta", "version"
  end
end
